### PR TITLE
dotnet-dump for windows/linux, full dumps only

### PR DESCRIPTION
**Pull request by anurse**
Early prototype of `dotnet-dump`. Supports Windows only and just captures a dump of all memory.

Based on anurse/add-dotnet-monitor

### CODE REVIEW

**Comment by anurse** [comment]
There are some non-sequitur changes because the initial import has some build failures in it.

**Comment by anurse** [comment]
Linux should work now, via locating `createdump` next to `libcoreclr.so`. Couldn't test it fully since `createdump` doesn't work on WSL :(

**Comment by anurse** [comment]
Waiting until #30 is merged before I merge this, since it's based on top of it. I'll probably just merge it on Monday if nobody has complained ;P

**Comment by davidfowl** [comment]
OK I'll play with this branch

**Pull request merged**
