### PR TITLE
Damienbod/add urls check

### PR DESCRIPTION
**Pull request by damienbod**
Adds a URLs check which returns Healthy, Unheathly and Warning depending on the Check parameters

### CODE REVIEW

**Comment by damienbod** [comment]
@anurse @glennc 
Here's a small pull request, the user can decide if the urls check is strict or not. 

Use Case, if I have n- Elasticsearch servers, it's still ok if maybe 1 URL is down. 
If I have n-URLs for different services, all must be healthy to start.

Thanks Damien

**Comment by glennc** [comment]
Need to rebase after merging other PR.

**Comment by damienbod** [comment]
Hi @glennc I rebased with the master

Thanks Damien

**Comment by natemcmaster** [comment]
Closing as this PR is stale.

**Pull request closed without merging**
