### PR TITLE
Adds experimental package for Minimal APIs template

### PR DESCRIPTION
**Pull request by DamianEdwards**
- Update SDK, Arcade and ./eng bits
- Add initial template project for 'dotnet new api'
- For now it's the same as empty web plus a comment in `Program.cs` and the `Properties/OpenApi.cs` file to auto-configure Swashbuckle at */openapi.json* and */docs*
- Contributes to dotnet/aspnetcore#34010

``` console
Template Name             Short Name  Language  Tags
------------------------  ----------  --------  -------
ASP.NET Core Minimal API  api         [C#]      Web/API
```

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]

**Comment by DamianEdwards** [comment]
@pranavkm any idea on the failures?

**Comment by pranavkm** [comment]
Looks like the same issue as https://github.com/aspnet/AspLabs/pull/359

**Comment by DamianEdwards** [comment]
@pranavkm shall I just merge and ping @JamesNK then?

**Comment by pranavkm** [comment]
It's not going to produce any packages so wouldn't be super helpful to merge it in the current state. Does making the one project not packable stop the error? Because that would be an acceptable solution.

**Comment by DamianEdwards** [comment]
ComponentsElectron? I can try.

**Comment by DamianEdwards** [comment]
@pranavkm what did I do wrong? How am I supposed to disable the projects from packing if not via the `<IsPackable>` property?

**Pull request merged**
