### PR TITLE
Azure storage health checks

### PR DESCRIPTION
**Pull request by JuergenGutsch**
I added some Azure Storage health checks and an sample project to show the usage:
- check the availability of the blob storage service
- check the availability of a container
- check the availability of the file storage service
- check the availability of a file share
- check the availability of the table storage service
- check the availability of a table
- check the availability of the queue service
- check the availability of a queue

### CODE REVIEW

**Comment by JuergenGutsch** [comment]
PR updated
@anurse @glennc

**Comment by glennc** [comment]
@JuergenGutsch Can we merge the sample apps into one?

**Comment by JuergenGutsch** [comment]
@glennc sure, we can :) should I do this?

**Comment by JuergenGutsch** [comment]
@glennc done. 
* I removed the azure sample app and added the sample usage to the other one
* I also updated the return values of the health checks to use the new return values

**Pull request merged**
